name: Create picgo folder

on:
  #schedule:
   # - cron: '0 15 * * *' # 东八区时间每天23:00执行
  push:
    branches:
      - main

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p picgo/$(date +%Y)/$(date +%m)/$(($(date +%d)+31))
          git config --global user.email "wk131013@163.com"
          git config --global user.name "sn-mumu"
          git add picgo/$(date +%Y)/$(date +%m)/$(($(date +%d)+31))
          git commit -m "Create folder for $(date +%Y-%m-%d+31)"
          git push origin main
