name: Create PicGo Folder

on:
  push:
    branches:
      - main
#on:
 # schedule:
  #  - cron: '0 15 * * *' # 东八区时间每天23:00执行

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create folder
        run: |
          mkdir -p PicGo/$(date +%Y)/$(date +%m)/$(($(date +%d)+1))
		  echo	"创建 PicGo/$(date +%Y)/$(date +%m)/$(($(date +%d)+1))"
		  git fetch
          echo 1
          git config --global user.email "wk131013@163.com"
          echo 3
          git config --global user.name "sn-mumu"
		  echo 2
		  git add .
          echo 4
          git commit -am "Create folder "
          echo 5
          git pull origin main
          echo 6
	  -	name: push folder
		uses: sn-mumu/github-push-action@main
		with:
		  github_token: ${{ secrets.GITHUB_TOKEN }}
      
